pipeline {
    agent any

    tools {
        nodejs 'NodeJS-18'
    }

    stages {

        stage('Clonar repositorio') {
            steps {
                git branch: 'develop',
                    url: 'https://github.com/JosueHernandez21/MovieExplorer.git'
            }
        }

        stage('Instalar dependencias') {
            steps {
                bat 'npm install'
            }
        }

        stage('Build Angular') {
            steps {
                sh 'npm run build -- --configuration=production'
            }
        }

        stage('Archivar artefacto') {
            steps {
                archiveArtifacts artifacts: 'dist/**', fingerprint: true
            }
        }
    }
}